const dict = {
  fr: {
    nav_fonctionnalites: "Fonctionnalités",
    nav_tarifs: "Tarifs",
    nav_faq: "FAQ",
    nav_connexion: "Se connecter",
    nav_essayer: "Essayer",
    photohero_titre1: "Votre activité.",
    photohero_titre2: "Votre contrôle.",
    photohero_tags: "Ventes • Dépenses • Résultats • Suivi à distance",
    photohero_cta: "PRENEZ LE CONTRÔLE",
    hero_eyebrow: "Pilotage financier simplifié",
    hero_titre: 'Votre caisse. <span class="accent">Votre résultat.</span> En un coup d\u2019œil.',
    hero_texte: "Enregistrez vos ventes et dépenses en quelques secondes. ComptaCi calcule votre résultat net, votre marge et votre TVA à provisionner — automatiquement.",
    hero_cta1: "Commencer maintenant",
    hero_cta2: "Voir comment ça marche",
    hero_langues: "🌍 Disponible en français, anglais et arabe",
    s_comment_kicker: "Comment ça marche",
    s_comment_titre: "De la caisse au bilan, en quatre étapes",
    step1_h: "Saisissez", step1_p: "Chaque vente et chaque dépense du jour, en quelques secondes depuis un téléphone.",
    step2_h: "Catégorisez", step2_p: "Boissons, nourriture, personnel, charges fixes — ComptaCi range tout automatiquement.",
    step3_h: "Visualisez", step3_p: "Tableau de bord clair : recettes, dépenses, marge, évolution mois par mois.",
    step4_h: "Décidez", step4_p: "Voyez immédiatement si votre établissement est rentable, et où part l'argent.",
    s_concu_kicker: "Conçu pour vous",
    s_concu_titre: "Pensé pour toutes les PME africaines de l'UEMOA",
    s_concu_sous: "Restaurants · Bars · Maquis · Hôtels · Quincailleries · Boutiques & épiceries · Salons de coiffure et beauté · Accessoires de téléphone · Boutiques de vêtements · Pharmacies",
    s_feat_postes_t: "20 dépenses types par métier",
    s_feat_postes_p: "Chaque activité affiche ses propres postes : biscuits, eau de javel, savon, bonbons, yaourt pour une boutique — faux ongles, vernis, perruques pour un salon.",
    s_feat_score_t: "Score de crédit",
    s_feat_score_p: "Vos données de gestion deviennent un score sur 100, avec une attestation à présenter à une banque ou une microfinance.",
    s_feat_fne_t: "Facture normalisée (FNE)",
    s_feat_fne_p: "Générez et archivez vos factures conformes à la DGI, depuis vos ventes enregistrées.",
    s_feat_fcfa_t: "Montants en FCFA",
    s_feat_fcfa_p: "Aucune conversion, aucune confusion. Tous les chiffres dans votre devise.",
    s_feat_paiement_t: "Paiement SasPay",
    s_feat_paiement_p: "Réglez par Mobile Money (Wave, Orange, MTN, Moov) ou carte bancaire, sans compte bancaire.",
    s_feat_simple_t: "Aucune notion comptable requise",
    s_feat_simple_p: "Vous saisissez ce que vous avez vendu et payé. ComptaCi fait le reste.",
    s_feat_multi_t: "Multi-établissements",
    s_feat_multi_p: "Gérez plusieurs points de vente depuis un seul compte, un accès par établissement.",
    s_feat_roles_t: "Gérant et propriétaire",
    s_feat_roles_p: "Le gérant saisit au quotidien, le propriétaire suit à distance en temps réel.",
    s_feat_mobile_t: "Accès depuis un téléphone",
    s_feat_mobile_p: "Aucune installation. Ouvrez simplement le lien depuis votre navigateur.",
    s_score_kicker: "Crédit",
    s_score_titre: "Vos chiffres peuvent vous ouvrir un crédit",
    s_score_c1_t: "Régularité des ventes",
    s_score_c1_p: "25 pts — enregistrez vos ventes chaque jour, sans trou.",
    s_score_c2_t: "Tendance du chiffre d'affaires",
    s_score_c2_p: "25 pts — croissance ou stabilité sur les derniers mois.",
    s_score_c3_t: "Dépenses maîtrisées",
    s_score_c3_p: "20 pts — ce que vous dépensez par rapport à ce que vous encaissez.",
    s_score_c4_t: "Ancienneté & abonnement",
    s_score_c4_p: "30 pts — un historique long et un abonnement à jour.",
    s_score_note: "Résultat : un score sur 100, avec des paliers Bronze, Argent et Or, et une attestation à remettre à votre banquier.",
    s_temoin_kicker: "Témoignages",
    s_temoin_titre: "Ils suivent déjà leur activité avec ComptaCi",
    f_eyebrow: "Offre limitée",
    f_titre: "Offre Fondateurs — 100 premiers établissements seulement",
    f_highlight: "★ Offre Fondateurs : 0 FCFA pendant 14 jours d'essai — ensuite, choix libre entre Starter, Pro ou Entreprise",
    f_abonnement: "0 FCFA pendant vos 14 jours d'essai — ensuite, choix libre entre le plan Starter, Pro ou Entreprise",
    plan_fondateur_note: "★ Offre Fondateurs (100 premiers établissements) : 0 FCFA pendant 14 jours d'essai, puis Starter (7 000), Pro (10 000) ou Entreprise (20 000) au choix",
    f_essai_14j: "14 jours d'essai gratuit, accès complet — 0 FCFA",
    f_cta: "Devenir établissement fondateur",
    p_kicker: "Tarifs",
    p_titre: "Une formule pour chaque étape de votre activité",
    p_note: "Sans engagement · Paiement mensuel par Mobile Money",
    plan_gratuit: "0 FCFA", plan_gratuit_per: "pendant 14 jours d'essai",
    plan_gratuit_1: "Accès complet au plan Starter pendant 14 jours",
    plan_gratuit_2: "Saisie des ventes et dépenses",
    plan_gratuit_3: "Tableau de bord et graphiques",
    plan_gratuit_4: "Choix du forfait après 14 jours",
    plan_essayer: "Essayer gratuitement",
    plan_populaire: "Le plus choisi",
    plan_par_mois: "par mois, par établissement",
    plan_1etab: "1 établissement",
    plan_saisie_illim: "Saisie illimitée des ventes et dépenses",
    plan_dashboard: "Tableau de bord et graphiques",
    plan_hist30: "Historique des 30 derniers jours",
    plan_tva: "Estimation TVA automatique",
    plan_pas_gerant: "1 gérant inclus",
    plan_commencer: "Commencer",
    plan_histcomplet: "Historique complet, sans limite",
    plan_gerant_illim: "Invitation de gérant illimitée",
    plan_multi_etab: "Établissements illimités",
    paiement_plan_entreprise: "Entreprise",
    faq_kicker: "FAQ", faq_titre: "Questions fréquentes",
    faq1_h: "Dois-je connaître la comptabilité pour utiliser ComptaCi ?",
    faq1_p: "Non. Vous saisissez simplement vos ventes et dépenses du jour ; ComptaCi calcule le reste.",
    faq2_h: "Comment fonctionne le paiement ?",
    faq2_p: "Le règlement mensuel se fait par SasPay — Mobile Money (Wave, Orange Money, MTN MoMo, Moov) ou carte bancaire — en un seul clic.",
    faq3_h: "Puis-je gérer plusieurs établissements ?",
    faq3_p: "Oui, chaque établissement dispose de son propre espace, accessible depuis un seul compte.",
    faq4_h: "Les chiffres de TVA sont-ils valables pour une déclaration officielle ?",
    faq4_p: "Non, ComptaCi est un outil de pilotage interne. Pour une déclaration fiscale, rapprochez-vous d'un comptable agréé.",
    faq5_h: "Que se passe-t-il à la fin des 14 jours d'essai ?",
    faq5_p: "Rien n'est prélevé automatiquement. Vous choisissez librement le plan Starter (7 000 FCFA/mois), Pro (10 000) ou Entreprise (20 000), ou vous arrêtez.",
    faq6_h: "Mon type d'établissement n'est pas dans la liste ?",
    faq6_p: "Choisissez le type le plus proche : chacun affiche plus de 20 postes de dépense adaptés à l'activité, et vous pouvez modifier ce choix à tout moment depuis votre espace Abonnement.",
    faq7_h: "Le score de crédit me garantit-il un prêt ?",
    faq7_p: "Non : c'est une preuve de gestion sérieuse que vous présentez à votre banque ou à votre institution de microfinance. ComptaCi travaille à le faire reconnaître par des partenaires bancaires.",
    faq8_h: "ComptaCi gère-t-il la facture normalisée (FNE) ?",
    faq8_p: "Oui, à partir du plan Pro. Vous devez d'abord être enrôlé auprès de la DGI : ComptaCi vous guide, génère vos factures, les transmet et les archive 10 ans.",
    cta_titre: "Prêt à voir clair sur votre rentabilité ?",
    cta_texte: "Rejoignez les gérants qui pilotent leur établissement au quotidien avec ComptaCi.",
    cta_btn: "Créer mon compte",
    footer_texte: "© 2026 ComptaCi — Pilotage financier pour restaurants, bars, maquis et hôtels en Côte d'Ivoire.",
  },
  en: {
    nav_fonctionnalites: "Features", nav_tarifs: "Pricing", nav_faq: "FAQ",
    nav_connexion: "Log in", nav_essayer: "Try it",
    photohero_titre1: "Your business.",
    photohero_titre2: "Your control.",
    photohero_tags: "Sales • Expenses • Results • Remote tracking",
    photohero_cta: "TAKE CONTROL",
    hero_eyebrow: "Simplified financial management",
    hero_titre: 'Your cash. <span class="accent">Your bottom line.</span> At a glance.',
    hero_texte: "Record your sales and expenses in seconds. ComptaCi automatically calculates your net result, margin, and VAT to set aside.",
    hero_cta1: "Get started now",
    hero_cta2: "See how it works",
    hero_langues: "🌍 Available in French, English and Arabic",
    s_comment_kicker: "How it works",
    s_comment_titre: "From cash register to report, in four steps",
    step1_h: "Record", step1_p: "Every sale and expense of the day, in seconds from a phone.",
    step2_h: "Categorize", step2_p: "Drinks, food, staff, fixed costs — ComptaCi sorts it all automatically.",
    step3_h: "Visualize", step3_p: "Clear dashboard: revenue, expenses, margin, month-by-month trend.",
    step4_h: "Decide", step4_p: "See instantly whether your business is profitable, and where the money goes.",
    s_concu_kicker: "Built for you",
    s_concu_titre: "Designed for every African SME in WAEMU",
    s_concu_sous: "Restaurants · Bars · Maquis · Hotels · Hardware stores · Grocery shops · Hair & beauty salons · Phone accessories · Clothing shops · Pharmacies",
    s_feat_postes_t: "20 typical expenses per trade",
    s_feat_postes_p: "Every trade shows its own items: biscuits, bleach, soap, sweets, yoghurt for a grocery — fake nails, nail polish, wigs for a salon.",
    s_feat_score_t: "Credit score",
    s_feat_score_p: "Your management data becomes a score out of 100, with a certificate to hand to a bank or microfinance institution.",
    s_feat_fne_t: "Standardised invoice (FNE)",
    s_feat_fne_p: "Create and archive DGI-compliant invoices straight from your recorded sales.",
    s_feat_fcfa_t: "Amounts in FCFA",
    s_feat_fcfa_p: "No conversion, no confusion. Every figure in your own currency.",
    s_feat_paiement_t: "SasPay checkout",
    s_feat_paiement_p: "Pay by mobile money (Wave, Orange, MTN, Moov) or card — no bank account needed.",
    s_feat_simple_t: "No accounting skills needed",
    s_feat_simple_p: "You enter what you sold and what you paid. ComptaCi does the rest.",
    s_feat_multi_t: "Multiple businesses",
    s_feat_multi_p: "Run several outlets from one account, with separate access for each.",
    s_feat_roles_t: "Manager and owner",
    s_feat_roles_p: "The manager enters data daily; the owner follows along remotely in real time.",
    s_feat_mobile_t: "Works on any phone",
    s_feat_mobile_p: "Nothing to install. Just open the link in your browser.",
    s_score_kicker: "Credit",
    s_score_titre: "Your numbers can unlock a loan",
    s_score_c1_t: "Sales consistency",
    s_score_c1_p: "25 pts — record your sales every day, with no gaps.",
    s_score_c2_t: "Revenue trend",
    s_score_c2_p: "25 pts — growth or stability over recent months.",
    s_score_c3_t: "Controlled spending",
    s_score_c3_p: "20 pts — what you spend against what you take in.",
    s_score_c4_t: "Track record & subscription",
    s_score_c4_p: "30 pts — a long history and an up-to-date subscription.",
    s_score_note: "The result: a score out of 100 with Bronze, Silver and Gold tiers, plus a certificate to hand to your banker.",
    s_temoin_kicker: "Testimonials",
    s_temoin_titre: "They already track their business with ComptaCi",
    f_eyebrow: "Limited offer",
    f_titre: "Founders Offer — First 100 businesses only",
    f_highlight: "★ Founders Offer: 0 FCFA for a 14-day trial — then free choice of Starter, Pro or Enterprise",
    f_abonnement: "0 FCFA for your 14-day trial — then free choice of Starter, Pro or Enterprise",
    plan_fondateur_note: "★ Founders Offer (first 100 businesses): 0 FCFA for 14 days, then Starter (7,000), Pro (10,000) or Enterprise (20,000)",
    f_essai_14j: "14-day free trial, full access — 0 FCFA",
    f_cta: "Become a founding business",
    p_kicker: "Pricing",
    p_titre: "A plan for every stage of your business",
    p_note: "No commitment · Monthly Mobile Money payment",
    plan_gratuit: "0 FCFA", plan_gratuit_per: "for a 14-day trial",
    plan_gratuit_1: "Full Starter-level access for 14 days",
    plan_gratuit_2: "Sales and expense entry",
    plan_gratuit_3: "Dashboard and charts",
    plan_gratuit_4: "Pick your plan after 14 days",
    plan_essayer: "Try for free",
    plan_populaire: "Most popular",
    plan_par_mois: "per month, per business",
    plan_1etab: "1 business",
    plan_saisie_illim: "Unlimited sales and expense entry",
    plan_dashboard: "Dashboard and charts",
    plan_hist30: "Last 30 days of history",
    plan_tva: "Automatic VAT estimate",
    plan_pas_gerant: "1 manager included",
    plan_commencer: "Get started",
    plan_histcomplet: "Full unlimited history",
    plan_gerant_illim: "Unlimited manager invitations",
    plan_multi_etab: "Unlimited businesses",
    paiement_plan_entreprise: "Enterprise",
    faq_kicker: "FAQ", faq_titre: "Frequently asked questions",
    faq1_h: "Do I need accounting knowledge to use ComptaCi?",
    faq1_p: "No. You simply enter your daily sales and expenses; ComptaCi does the rest.",
    faq2_h: "How does payment work?",
    faq2_p: "The monthly payment runs through SasPay — mobile money (Wave, Orange Money, MTN MoMo, Moov) or card — in one click.",
    faq3_h: "Can I manage multiple businesses?",
    faq3_p: "Yes, each business has its own space, accessible from a single account.",
    faq4_h: "Are the VAT figures valid for an official tax return?",
    faq4_p: "No, ComptaCi is an internal management tool. For a tax return, consult a licensed accountant.",
    faq5_h: "What happens when the 14-day trial ends?",
    faq5_p: "Nothing is charged automatically. You freely choose Starter (7,000 FCFA/month), Pro (10,000) or Enterprise (20,000) — or you simply stop.",
    faq6_h: "My type of business is not in the list?",
    faq6_p: "Pick the closest one: each type shows more than 20 expense items fitted to the trade, and you can change it any time from your Subscription area.",
    faq7_h: "Does the credit score guarantee me a loan?",
    faq7_p: "No: it is evidence of sound management that you present to your bank or microfinance institution. ComptaCi is working to have it recognised by banking partners.",
    faq8_h: "Does ComptaCi handle the standardised invoice (FNE)?",
    faq8_p: "Yes, from the Pro plan upwards. You must first be enrolled with the DGI: ComptaCi guides you, generates your invoices, transmits them and archives them for 10 years.",
    cta_titre: "Ready to see your profitability clearly?",
    cta_texte: "Join the managers who run their business day-to-day with ComptaCi.",
    cta_btn: "Create my account",
    footer_texte: "© 2026 ComptaCi — Financial management for restaurants, bars and hotels in Côte d'Ivoire.",
  },
  ar: {
    nav_fonctionnalites: "الميزات", nav_tarifs: "الأسعار", nav_faq: "الأسئلة الشائعة",
    nav_connexion: "تسجيل الدخول", nav_essayer: "جرّب الآن",
    photohero_titre1: "نشاطك.",
    photohero_titre2: "تحت سيطرتك.",
    photohero_tags: "مبيعات • مصاريف • نتائج • متابعة عن بعد",
    photohero_cta: "تحكّم الآن",
    hero_eyebrow: "إدارة مالية مبسطة",
    hero_titre: 'صندوقك. <span class="accent">نتيجتك.</span> بنظرة واحدة.',
    hero_texte: "سجّل مبيعاتك ومصاريفك في ثوانٍ. يحسب ComptaCi تلقائياً نتيجتك الصافية وهامشك وضريبة القيمة المضافة الواجب توفيرها.",
    hero_cta1: "ابدأ الآن",
    hero_cta2: "شاهد كيف يعمل",
    hero_langues: "🌍 متوفر بالفرنسية والإنجليزية والعربية",
    s_comment_kicker: "كيف يعمل",
    s_comment_titre: "من الصندوق إلى التقرير، في أربع خطوات",
    step1_h: "سجّل", step1_p: "كل بيع ومصروف لليوم، في ثوانٍ من هاتفك.",
    step2_h: "صنّف", step2_p: "مشروبات، طعام، موظفون، مصاريف ثابتة — يرتب ComptaCi كل شيء تلقائياً.",
    step3_h: "تصوّر", step3_p: "لوحة تحكم واضحة: الإيرادات، المصاريف، الهامش، التطور شهراً بشهر.",
    step4_h: "قرّر", step4_p: "اعرف فوراً إن كانت منشأتك رابحة، وأين يذهب المال.",
    s_concu_kicker: "مصمم من أجلك",
    s_concu_titre: "مصمم لجميع المؤسسات الصغيرة والمتوسطة الأفريقية في الاتحاد الاقتصادي والنقدي لغرب أفريقيا",
    s_concu_sous: "مطاعم · بارات · مطاعم شعبية · فنادق · محلات أدوات · بقالات · صالونات حلاقة وتجميل · ملحقات الهاتف · محلات ملابس · صيدليات",
    s_feat_postes_t: "20 بند مصاريف لكل مهنة",
    s_feat_postes_p: "يعرض كل نشاط بنوده الخاصة: بسكويت، ماء جافيل، صابون، حلويات، ياغورت للبقالة — أظافر اصطناعية، طلاء أظافر، شعر مستعار للصالون.",
    s_feat_score_t: "درجة الائتمان",
    s_feat_score_p: "تتحول بيانات تسييركم إلى درجة من 100، مع شهادة تُقدَّم إلى بنك أو مؤسسة تمويل أصغر.",
    s_feat_fne_t: "الفاتورة المعيارية (FNE)",
    s_feat_fne_p: "أنشئوا فواتيركم المطابقة للمديرية العامة للضرائب وأرشفوها انطلاقاً من مبيعاتكم المسجلة.",
    s_feat_fcfa_t: "المبالغ بالفرنك الإفريقي",
    s_feat_fcfa_p: "لا تحويل ولا لبس. كل الأرقام بعملتكم.",
    s_feat_paiement_t: "الدفع عبر SasPay",
    s_feat_paiement_p: "ادفعوا بالمال عبر الهاتف (Wave أو Orange أو MTN أو Moov) أو بالبطاقة البنكية، دون حساب بنكي.",
    s_feat_simple_t: "لا حاجة لأي معرفة محاسبية",
    s_feat_simple_p: "تسجلون ما بعتم وما دفعتم. يتولى ComptaCi الباقي.",
    s_feat_multi_t: "عدة منشآت",
    s_feat_multi_p: "أديروا عدة نقاط بيع من حساب واحد، مع وصول مستقل لكل منشأة.",
    s_feat_roles_t: "المسيّر والمالك",
    s_feat_roles_p: "المسيّر يسجل يومياً، والمالك يتابع عن بُعد وفي الوقت الفعلي.",
    s_feat_mobile_t: "الوصول من الهاتف",
    s_feat_mobile_p: "لا شيء لتثبيته. افتحوا الرابط في متصفحكم فقط.",
    s_score_kicker: "الائتمان",
    s_score_titre: "يمكن لأرقامكم أن تفتح لكم باب القرض",
    s_score_c1_t: "انتظام المبيعات",
    s_score_c1_p: "25 نقطة — سجلوا مبيعاتكم كل يوم دون انقطاع.",
    s_score_c2_t: "اتجاه رقم الأعمال",
    s_score_c2_p: "25 نقطة — نمو أو استقرار خلال الأشهر الأخيرة.",
    s_score_c3_t: "التحكم في المصاريف",
    s_score_c3_p: "20 نقطة — ما تصرفونه مقابل ما تقبضونه.",
    s_score_c4_t: "الأقدمية والاشتراك",
    s_score_c4_p: "30 نقطة — سجل طويل واشتراك مسدَّد.",
    s_score_note: "النتيجة: درجة من 100 بمستويات برونزي وفضي وذهبي، مع شهادة تُسلَّم للموظف البنكي.",
    s_temoin_kicker: "الشهادات",
    s_temoin_titre: "يتابعون نشاطهم بالفعل مع ComptaCi",
    f_eyebrow: "عرض محدود",
    f_titre: "عرض المؤسسين — أول 100 منشأة فقط",
    f_highlight: "★ عرض المؤسسين: 0 فرنك خلال 14 يوماً من التجربة — ثم الاختيار حر بين Starter وPro وEntreprise",
    f_abonnement: "0 فرنك خلال 14 يوماً من التجربة — ثم الاختيار حر بين Starter وPro وEntreprise",
    f_essai_14j: "14 يوماً من التجربة المجانية، وصول كامل — 0 فرنك",
    plan_fondateur_note: "★ عرض المؤسسين (أول 100 منشأة): 0 فرنك خلال 14 يوماً من التجربة، ثم Starter (7,000) أو Pro (10,000) أو Entreprise (20,000)",
    f_cta: "كن منشأة مؤسسة",
    p_kicker: "الأسعار",
    p_titre: "باقة لكل مرحلة من نشاطك",
    p_note: "بدون التزام · دفع شهري عبر Mobile Money",
    plan_gratuit: "0 فرنك", plan_gratuit_per: "خلال 14 يوماً من التجربة",
    plan_gratuit_1: "وصول كامل بمستوى Starter لمدة 14 يوماً",
    plan_gratuit_2: "تسجيل المبيعات والمصاريف",
    plan_gratuit_3: "لوحة التحكم والرسوم البيانية",
    plan_gratuit_4: "اختيار الباقة بعد 14 يوماً",
    plan_essayer: "جرّب مجاناً",
    plan_populaire: "الأكثر اختياراً",
    plan_par_mois: "شهرياً، لكل منشأة",
    plan_1etab: "منشأة واحدة",
    plan_saisie_illim: "تسجيل غير محدود للمبيعات والمصاريف",
    plan_dashboard: "لوحة التحكم والرسوم البيانية",
    plan_hist30: "سجل آخر 30 يوماً",
    plan_tva: "تقدير تلقائي لضريبة القيمة المضافة",
    plan_pas_gerant: "مدير واحد مشمول",
    plan_commencer: "ابدأ",
    plan_histcomplet: "سجل كامل بدون حدود",
    plan_gerant_illim: "دعوات مدير غير محدودة",
    plan_multi_etab: "منشآت غير محدودة",
    paiement_plan_entreprise: "Entreprise",
    faq_kicker: "الأسئلة الشائعة", faq_titre: "أسئلة متكررة",
    faq1_h: "هل أحتاج إلى معرفة محاسبية لاستخدام ComptaCi؟",
    faq1_p: "لا. تقوم فقط بإدخال مبيعاتك ومصاريفك اليومية؛ يتكفل ComptaCi بالباقي.",
    faq2_h: "كيف يعمل الدفع؟",
    faq2_p: "يتم الدفع الشهري عبر SasPay — المال عبر الهاتف (Wave أو Orange Money أو MTN MoMo أو Moov) أو البطاقة البنكية — بنقرة واحدة.",
    faq3_h: "هل يمكنني إدارة عدة منشآت؟",
    faq3_p: "نعم، لكل منشأة مساحتها الخاصة، يمكن الوصول إليها من حساب واحد.",
    faq4_h: "هل أرقام ضريبة القيمة المضافة صالحة للإقرار الضريبي الرسمي؟",
    faq4_p: "لا، ComptaCi أداة إدارة داخلية. للإقرار الضريبي، توجه إلى محاسب معتمد.",
    faq5_h: "ماذا يحدث بعد انتهاء فترة التجربة (14 يوماً)؟",
    faq5_p: "لا يُخصم أي مبلغ تلقائياً. تختارون بحرية باقة Starter (7,000 فرنك/شهر) أو Pro (10,000) أو Entreprise (20,000)، أو تتوقفون.",
    faq6_h: "نوع منشأتي غير موجود في القائمة؟",
    faq6_p: "اختاروا النوع الأقرب: يعرض كل نوع أكثر من 20 بند مصاريف ملائماً للنشاط، ويمكنكم تعديل هذا الاختيار في أي وقت من مساحة الاشتراك.",
    faq7_h: "هل تضمن لي درجة الائتمان الحصول على قرض؟",
    faq7_p: "لا: إنها دليل على حسن التسيير تقدمونه لبنكم أو مؤسسة التمويل الأصغر. ويعمل ComptaCi على الاعتراف بها لدى شركاء بنكيين.",
    faq8_h: "هل يتكفل ComptaCi بالفاتورة المعيارية (FNE)؟",
    faq8_p: "نعم، ابتداءً من باقة Pro. يجب أولاً التسجيل لدى المديرية العامة للضرائب: يرشدكم ComptaCi، وينشئ فواتيركم، ويرسلها ويؤرشفها 10 سنوات.",
    cta_titre: "مستعد لرؤية ربحيتك بوضوح؟",
    cta_texte: "انضم إلى المدراء الذين يديرون نشاطهم يومياً مع ComptaCi.",
    cta_btn: "إنشاء حسابي",
    footer_texte: "© 2026 ComptaCi — إدارة مالية للمطاعم والبارات والفنادق في كوت ديفوار.",
  },
};

const RTL = ["ar"];

function getLangueInitiale() {
  try {
    const sauvegardee = localStorage.getItem("comptaci:langue");
    if (sauvegardee && dict[sauvegardee]) return sauvegardee;
  } catch (e) {}
  return "fr";
}

function appliquerLangue(langue) {
  const table = dict[langue] || dict.fr;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const cle = el.getAttribute("data-i18n");
    if (table[cle]) el.textContent = table[cle];
  });
  document.querySelectorAll("[data-i18n-html]").forEach((el) => {
    const cle = el.getAttribute("data-i18n-html");
    if (table[cle]) el.innerHTML = table[cle];
  });
  document.documentElement.lang = langue;
  document.documentElement.dir = RTL.includes(langue) ? "rtl" : "ltr";
  const select = document.getElementById("lang-select");
  if (select) select.value = langue;
  try {
    localStorage.setItem("comptaci:langue", langue);
  } catch (e) {}
}

document.addEventListener("DOMContentLoaded", () => {
  const langueInitiale = getLangueInitiale();
  appliquerLangue(langueInitiale);
  const select = document.getElementById("lang-select");
  if (select) {
    select.addEventListener("change", (e) => appliquerLangue(e.target.value));
  }
});

// --- Compteur de places fondateurs restantes (déjà existant) ---
import { supabase, configManquante } from "./supabaseClient.js";

async function afficherPlacesRestantes() {
  const el = document.getElementById("fondateur-slots");
  if (!el) return;
  if (configManquante || !supabase) {
    el.textContent = "Places limitées";
    return;
  }
  try {
    const { data, error } = await supabase.rpc("places_fondateurs_restantes");
    if (error || data == null) {
      el.textContent = "Places limitées";
      return;
    }
    el.textContent = data > 0
      ? `${data} place${data > 1 ? "s" : ""} restante${data > 1 ? "s" : ""} sur 100`
      : "Offre fondateurs complète — tarif normal désormais";
  } catch (e) {
    el.textContent = "Places limitées";
  }
}

afficherPlacesRestantes();
